---
name: Anya Danilova
job: QA Engineer
level: junior
email: eternalgrey43@gmail.com
description: |
  Мне кажется, тестирование/программирование, это творческий процесс.

  Вне работы я занимаюсь коммерческой фотографией, мне нравится сочетать IT и art.
skills: 
  - Функциональное тестирование
  - Написание багрепортов
  - Слепая печать
  - Английский язык B2
  - Навыки работы в Devtools