---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность фильтровать товары по категориям, так как представлены товары разных категорий
  - При смене языка должны устанавливаться цены в валюте выбранной страны
  - В карточке товара должно отображаться оставшееся количество конкретного товара
  - В карточке товара должен быть тег, при тапе на который должен происходить переход в категорию
  - В карточке товара цена должна быть показана со скидкой